name: Delete Old Workflow Runs

on:
  schedule:
    # Runs at midnight on the 1st of every month
    - cron: '0 0 1 * *'
  workflow_dispatch: # Allows manual trigger from the Actions tab

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 30
          keep_minimum_runs: 5
